# Generated by Django 4.2.11 on 2024-03-19 07:47

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Counties',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objectid', models.IntegerField()),
                ('county_nam', models.CharField(max_length=50)),
                ('count', models.FloatField()),
                ('shape_leng', models.FloatField()),
                ('shape_area', models.FloatField()),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
            options={
                'verbose_name_plural': 'Counties',
            },
        ),
        migrations.CreateModel(
            name='Incidences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
            options={
                'verbose_name_plural': 'Incidences',
            },
        ),
        migrations.CreateModel(
            name='Parcels',
            fields=[
                ('id', models.IntegerField()),
                ('rim_source', models.CharField(max_length=50, null=True)),
                ('area_in_ha', models.FloatField()),
                ('reg_block', models.CharField(blank=True, max_length=100, null=True)),
                ('boundary_s', models.CharField(blank=True, max_length=50, null=True)),
                ('parcel_no', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
            options={
                'verbose_name_plural': 'Parcels',
            },
        ),
        migrations.CreateModel(
            name='PowerLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geom', django.contrib.gis.db.models.fields.MultiLineStringField(srid=4326)),
                ('name', models.CharField(default='Phaseload', max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Power line',
            },
        ),
        migrations.CreateModel(
            name='StudyArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geom', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
                ('name', models.CharField(default='Nyeri View', max_length=50)),
            ],
            options={
                'verbose_name_plural': 'StudyArea',
            },
        ),
        migrations.CreateModel(
            name='VoltageData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'VoltageData',
            },
        ),
    ]
