# Generated by Django 4.2.11 on 2024-03-20 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_cadastral_delete_parcels'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadastral',
            name='popupinfo',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='cadastral',
            name='snippet',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
