# Generated by Django 5.0.1 on 2024-01-24 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_studyarea_alter_counties_objectid'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studyarea',
            options={'verbose_name_plural': 'StudyAreas'},
        ),
    ]
