# Generated by Django 5.0.1 on 2024-01-24 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_studyarea_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studyarea',
            options={'verbose_name_plural': 'StudyArea'},
        ),
    ]
