# Generated by Django 5.0.1 on 2024-01-26 08:28

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_studyarea_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studyarea',
            name='geom',
            field=django.contrib.gis.db.models.fields.PolygonField(srid=4326),
        ),
    ]
