# Generated by Django 4.2.11 on 2024-03-21 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_branches'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branches',
            name='popupinfo',
            field=models.CharField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='branches',
            name='snippet',
            field=models.CharField(max_length=254, null=True),
        ),
    ]
