# Generated by Django 4.2.11 on 2024-03-21 14:14

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_branches_popupinfo_alter_branches_snippet'),
    ]

    operations = [
        migrations.CreateModel(
            name='Households',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('folderpath', models.CharField(max_length=254)),
                ('symbolid', models.BigIntegerField()),
                ('altmode', models.IntegerField()),
                ('base', models.FloatField()),
                ('snippet', models.CharField(max_length=254, null=True)),
                ('popupinfo', models.CharField(max_length=254, null=True)),
                ('haslabel', models.IntegerField()),
                ('labelid', models.BigIntegerField()),
                ('geom', django.contrib.gis.db.models.fields.MultiPointField(srid=4326)),
            ],
        ),
    ]
