# Generated by Django 5.0.1 on 2024-01-26 15:28

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_voltagedata'),
    ]

    operations = [
        migrations.CreateModel(
            name='PowerLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geom', django.contrib.gis.db.models.fields.LineStringField(srid=4326)),
            ],
        ),
        migrations.AlterModelOptions(
            name='voltagedata',
            options={'verbose_name_plural': 'VoltageData'},
        ),
    ]
