# Generated by Django 5.0.1 on 2024-01-27 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_powerline_alter_voltagedata_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='powerline',
            options={'verbose_name_plural': 'Power line'},
        ),
        migrations.AddField(
            model_name='powerline',
            name='name',
            field=models.CharField(default='Phase', max_length=50),
        ),
    ]
