# Generated by Django 5.0.1 on 2024-01-27 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_powerline_options_powerline_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='studyarea',
            name='name',
            field=models.CharField(default='Nyeri View', max_length=50),
        ),
    ]
